# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d315e661d8e93af6286bd270728fbefd1916be056e7a047a37a431e5643a8a583eed2325aee318681f30b5874160ef26075fbbaba9608c8308b243512c280904

test:
  secret_key_base: d6e15bccf61e9e9d8c9bdd02496cd6cfce8e33f99fc710257945f60153b31accf3ac0464c3bb4a94e84f547d8aac4c6d7385eaf96979181b7a6f79dff066e48d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
